'
' Created by SharpDevelop.
' User: diego.fernandez
' Date: 09.06.2022
' Time: 11:00
' 
' To change this template use Tools | Options | Coding | Edit Standard Headers.
'
Imports System
Imports Autodesk.Revit.UI
Imports Autodesk.Revit.DB
Imports Autodesk.Revit.UI.Selection
Imports System.Collections.Generic
Imports System.Linq

<Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)> _
<Autodesk.Revit.DB.Macros.AddInId("EBB018F2-6E45-42BA-80CB-63E5101B7D8F")> _
Partial Public Class ThisDocument

    Private Sub Module_Startup(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Startup
	
    End Sub
	
    Private Sub Module_Shutdown(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Shutdown
	
    End Sub
	
	Public Sub Myfirstmacro()
		
		Dim currentDoc As Document = Me.Application.ActiveUIDocument.Document
		
		Dim viewCollector = New FilteredElementCollector(currentDoc)
		
		viewCollector.OfCategory(BuiltInCategory.OST_Views)
		
		Dim sheetCollector = New FilteredElementCollector(currentDoc)
		
		sheetCollector.OfCategory(BuiltInCategory.OST_Sheets)
		
		TaskDialog.Show("My first macro", "this is " & Me.Application.ActiveUIDocument.ActiveView.Name)
		
		TaskDialog.Show("My first macro", " Views are " & viewCollector.Count)
		
		TaskDialog.Show("My first macro", " Sheets are " & sheetCollector.Count)
		
	End Sub
End Class
